"""Render docs/evaluation.md and docs/model_card.md (+ artifacts/model_card.json) from artifacts.

Every number in these documents is read from artifacts produced by the pipeline;
nothing is typed by hand. Run after `python -m forecast_bust.evaluate` and `... .replay`.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ART = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else ROOT / "artifacts"


def load(name):
    p = ART / name
    return json.loads(p.read_text()) if p.exists() else None


def f(v, n=3):
    return "—" if v is None else f"{v:.{n}f}"


def main():
    m, ab, ss, fp, man, th, pca, imp = (load(x) for x in (
        "metrics.json", "ablation_results.json", "spread_skill.json", "fingerprint_metrics.json",
        "experiment_manifest.json", "thresholds.json", "pca.json", "feature_importance.json"))
    if m is None:
        raise SystemExit("metrics.json missing: run the pipeline first")
    M = m["models"]
    fv = m["full_vs_b2"]
    sp = m["dataset"]["splits"]
    L = []
    w = L.append
    w("# Evaluation (generated from artifacts — do not edit by hand)\n")
    w(f"Generated by `scripts/write_reports.py` from `{ART.relative_to(ROOT)}/`. Experiment git revision "
      f"`{man['git_rev'] if man else '?'}`, seed {man['seed'] if man else '?'}.\n")
    w("## Data and split\n")
    w(f"* Source: {m['dataset']['source']} (`{m['dataset']['forecast_store']}`); target: {m['dataset']['target']}.")
    w(f"* Reference: {m['dataset']['reference']}.")
    w("\n| Split | Initialisations | First init | Last init | Region×day rows | Bust rate |\n|---|---:|---|---|---:|---:|")
    for k in ("train", "validation", "test", "embargo"):
        if k in sp:
            s = sp[k]
            w(f"| {k} | {s['inits']} | {s['first_init'][:13]} | {s['last_init'][:13]} | {s['rows']} | {f(s['bust_rate'])} |")
    w("\n`embargo` = rows whose verification falls after the end of their period (purged from fitting).\n")
    w("## Headline: does Sentinel beat the calibrated spread-only baseline (B2)?\n")
    verdict = ("**Material improvement established**" if fv["material_improvement"]
               else "**Incremental predictive value NOT established**")
    w(f"{verdict} under the rule fixed before the test evaluation ({fv['verdict_rule']}).\n")
    w(f"* AUPRC FULL {f(M['FULL']['auprc'])} vs B2 {f(M['B2']['auprc'])} (test base rate {f(m['test_base_rate'])}).")
    w(f"* Difference {f(fv['auprc_gain'], 4)} ({100 * fv['relative_gain']:.1f}% relative); 95% block-bootstrap CI "
      f"[{f(fv['bootstrap']['ci95'][0], 4)}, {f(fv['bootstrap']['ci95'][1], 4)}], {fv['bootstrap']['n_boot']} resamples "
      f"of {fv['bootstrap']['block']}s; P(diff ≤ 0) = {f(fv['bootstrap']['p_le_0'], 3)}.\n")
    w("## Model comparison and ablation (TEST, n = {:,} region×day cases)\n".format(m["n_test_rows"]))
    w("| Model | Description | AUPRC | ROC AUC | Brier | ECE | Recall@FAR5% | Recall@FAR10% | Hidden-bust recall | "
      "Low-spread AUPRC | Mean lead day of detected busts |\n|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for k in ("B0", "B1", "B2", "M1", "M2", "M3", "M4", "M5", "M6", "ALL", "FULL"):
        r = M[k]
        w(f"| {k} | {r['description']} | {f(r['auprc'])} | {f(r['roc_auc'])} | {f(r['brier'], 4)} | {f(r['ece'], 4)} | "
          f"{f(r['recall_at_far_5'])} | {f(r['recall_at_far_10'])} | {f(r['hidden_bust']['hidden_bust_recall'])} | "
          f"{f(r['hidden_bust']['low_spread_auprc'])} | {f(r['warning_lead']['mean_lead_day_of_detected_busts'], 2)} |")
    w("\nB1 is a ranking score, so Brier/ECE are not applicable. Hidden-bust recall uses each model's operating "
      "threshold chosen on VALIDATION for a 10% false-alarm rate.\n")
    w("### Operating point (threshold chosen on validation, FAR target 10%)\n")
    w("| Model | Threshold | Precision | Recall | Test FAR | Hidden busts (n) |\n|---|---:|---:|---:|---:|---:|")
    for k in ("B2", "FULL"):
        o = M[k]["operating_point"]
        w(f"| {k} | {f(o['threshold'])} | {f(o['precision'])} | {f(o['recall'])} | {f(o['false_alarm_rate'])} | "
          f"{M[k]['hidden_bust']['n_hidden_busts']} |")
    w("\n### By lead day (AUPRC)\n\n| Day | Bust rate | B0 | B2 | FULL |\n|---:|---:|---:|---:|---:|")
    for r in m["by_lead_day"]:
        w(f"| {r['lead_day']} | {f(r['bust_rate'])} | {f(r['auprc_B0'])} | {f(r['auprc_B2'])} | {f(r['auprc_FULL'])} |")
    w("\n### By season (AUPRC)\n\n| Season | n | Bust rate | B2 | FULL |\n|---|---:|---:|---:|---:|")
    for r in m["by_season"]:
        w(f"| {r['season']} | {r['n']} | {f(r['bust_rate'])} | {f(r['auprc_B2'])} | {f(r['auprc_FULL'])} |")
    w("\n### Derived-product diagnostics\n")
    for k in ("B2", "FULL"):
        r = M[k]
        w(f"* {k}: peak-risk-day error {f(r['peak_risk_day']['mean_abs_peak_day_error'], 2)} days "
          f"(within ±1 day {f(r['peak_risk_day']['within_1_day'])}; {r['peak_risk_day']['n_trajectories']} trajectories); "
          f"mean spatial Jaccard overlap {f(r['spatial_overlap']['mean_jaccard'])} over {r['spatial_overlap']['n_maps']} maps.")
    w("\n### Sensitivity\n")
    q = m["q95_sensitivity"]
    w(f"* Q95 bust criterion (models retrained with the same protocol): AUPRC B0 {f(q['B0']['auprc'])}, "
      f"B2 {f(q['B2']['auprc'])}, FULL {f(q['FULL']['auprc'])}.")
    w(f"* Frozen historical memory (train+validation only): FULL AUPRC {f(m['frozen_memory_sensitivity']['auprc'])} "
      f"(causal-online memory: {f(M['FULL']['auprc'])}).")
    w("\n### Evidence strength vs outcome (TEST)\n\n| Evidence | n | Mean FULL p | Observed bust rate |\n|---|---:|---:|---:|")
    for r in m["by_evidence_level"]:
        w(f"| {r['evidence']} | {r['n']} | {f(r['mean_p_FULL'])} | {f(r['bust_rate'])} |")
    if fp:
        w("\n## Failure-signature memory (TEST busts)\n")
        w(f"* {fp['n_test_busts']} test busts; {fp['n_with_analogue_expectation']} had an analogue-based expectation.")
        w(f"* Top-1 agreement: analogues {f(fp['top1_agreement'])} vs climatological reference "
          f"({fp['reference_climatological_top1']}) {f(fp['reference_top1_agreement'])}.")
        w(f"* Mean probability assigned to the actual signature: analogues {f(fp['mean_prob_assigned_to_actual'])} vs "
          f"reference {f(fp['reference_mean_prob_assigned'])}.")
        w(f"* Actual test signature frequencies: " + ", ".join(f"{k} {v:.2f}" for k, v in fp['actual_test_signature_frequencies'].items()))
    if ss:
        w("\n## Spread–skill diagnostics of the IFS ENS itself (TEST, target regions)\n")
        w("| Day | RMSE (m) | Spread (m) | Spread/skill | corr(spread, error) |\n|---:|---:|---:|---:|---:|")
        for r in ss["per_lead"]:
            w(f"| {r['lead_day']} | {f(r['rmse_m'], 1)} | {f(r['spread_m'], 1)} | {f(r['spread_skill_ratio'], 2)} | {f(r['corr_spread_error'], 2)} |")
        w(f"\nRank histograms per lead day are in `spread_skill.json` ({ss['n_members']} members). {ss['note']}.")
    if imp:
        top = list(imp["FULL"].items())[:12]
        w("\n## FULL model: top features by total gain\n\n| Feature | Share of gain |\n|---|---:|")
        for k, v in top:
            w(f"| {k} | {v:.3f} |")
    w("\n## How to reproduce\n\n```bash\nscripts/download_all.sh\npython -m forecast_bust.train\npython -m forecast_bust.evaluate\n"
      "python -m forecast_bust.replay\npython scripts/write_reports.py\n```")
    (ROOT / "docs" / "evaluation.md").write_text("\n".join(L) + "\n")

    card = {
        "name": "Forecast Bust Sentinel (FULL)", "version": "0.1.0",
        "intended_use": "Research decision support: regional Day 1-10 probability that an existing NWP ensemble-mean "
                        "Z500 forecast exceeds a project-defined large-error threshold; forecaster triage.",
        "not_intended_use": ["weather-event probabilities", "replacement NWP forecast", "local/point forecasts",
                             "operational warnings without forecaster review", "NCMRWF forecasts (not trained on them)"],
        "dataset": m["dataset"], "target": "Z500 regional error of the IFS ENS ensemble mean vs ERA5",
        "bust_definition": th["definition"] if th else None, "sensitivity": th["sensitivity"] if th else None,
        "feature_groups": man["feature_groups"] if man else None,
        "model": "XGBoost (hist, CPU) + isotonic calibration on validation",
        "hyperparameters": man["model_config"]["xgboost"] if man else None,
        "chronology": {k: {kk: sp[k][kk] for kk in ("first_init", "last_init", "inits")} for k in sp},
        "metrics": {k: {"auprc": M[k]["auprc"], "brier": M[k]["brier"], "roc_auc": M[k]["roc_auc"]} for k in M},
        "full_vs_b2": fv, "pca": pca,
        "limitations": "docs/limitations.md",
    }
    (ART / "model_card.json").write_text(json.dumps(card, indent=1, default=str))
    C = ["# Model card — Forecast Bust Sentinel (generated from artifacts)\n",
         "## Intended use\n", card["intended_use"], "\n## Not intended for\n"] + [f"* {x}" for x in card["not_intended_use"]]
    C += ["\n## Data\n", f"* Forecasts: {m['dataset']['source']} (`{m['dataset']['forecast_store']}`)",
          f"* Verification: {m['dataset']['reference']}",
          "* Anomaly climatology: ERA5 1990–2017 (pre-dates all experiment years)",
          "* Chronological split: " + "; ".join(f"{k} {v['first_init'][:10]}..{v['last_init'][:10]} ({v['inits']} inits)"
                                                for k, v in sp.items()),
          "\n## Target and label\n", f"* {card['bust_definition']}", f"* Sensitivity: {card['sensitivity']}",
          "\n## Model\n", f"* {card['model']}; hyperparameters fixed in `config/model.yaml`; early stopping on validation.",
          "* Feature groups: SPREAD (B2 inputs), ATM, ENS, PAT (frozen TRAIN PCA), EVO, MEM (causal analogue memory).",
          "\n## Validation / test methodology\n",
          "* Development on a separate dev split (2018–19 / 2020 / 2021); final 2022 test evaluated once.",
          f"* Primary metric AUPRC; verdict rule: {fv['verdict_rule']}.",
          "\n## Results (TEST)\n", "| Model | AUPRC | Brier | ROC AUC |", "|---|---:|---:|---:|"]
    C += [f"| {k} | {f(v['auprc'])} | {f(v['brier'], 4)} | {f(v['roc_auc'])} |" for k, v in card["metrics"].items()]
    C += ["", f"Improvement over B2 material: **{fv['material_improvement']}** (AUPRC gain {f(fv['auprc_gain'], 4)}, "
              f"CI {f(fv['bootstrap']['ci95'][0], 4)}..{f(fv['bootstrap']['ci95'][1], 4)}).",
          "\n## Known failure modes and limitations\n",
          "* Weak historical support for novel states (reported as evidence/support categories).",
          "* Relationships are specific to ECMWF IFS ENS 2018–2022 and to the 5.625° grid; NWP upgrades cause drift.",
          "* ERA5 is a reference analysis, not truth; Q90 bust criterion is project-defined; Z500 only.",
          "* Full list: `docs/limitations.md`. Full metrics: `docs/evaluation.md`."]
    (ROOT / "docs" / "model_card.md").write_text("\n".join(C) + "\n")
    print("wrote docs/evaluation.md, docs/model_card.md, model_card.json")


if __name__ == "__main__":
    main()
